# Generated by Django 3.2.5 on 2021-08-12 00:33

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('pacientes', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='obrasocial',
            options={'verbose_name': 'obra social', 'verbose_name_plural': 'obras sociales'},
        ),
    ]
