# Generated by Django 3.2.5 on 2021-08-28 21:23

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('pacientes', '0002_alter_obrasocial_options'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='paciente',
            name='apellido',
        ),
        migrations.RemoveField(
            model_name='paciente',
            name='dni',
        ),
        migrations.RemoveField(
            model_name='paciente',
            name='domicilio',
        ),
        migrations.RemoveField(
            model_name='paciente',
            name='obra_social',
        ),
        migrations.RemoveField(
            model_name='paciente',
            name='observaciones',
        ),
        migrations.DeleteModel(
            name='Domicilio',
        ),
        migrations.DeleteModel(
            name='ObraSocial',
        ),
    ]
