# Generated by Django 3.2.5 on 2021-08-16 22:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ventas', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='producto',
            name='categoria',
            field=models.CharField(choices=[('Lentes', 'Lentes'), ('Armazones', 'Armazones'), ('Accesorios', 'Accesorios'), ('Ortóptica', 'Ortoptica'), ('Otras', 'Otras')], max_length=10),
        ),
    ]
