# Generated by Django 3.2.5 on 2021-08-23 03:28

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('pacientes', '0002_alter_obrasocial_options'),
        ('ventas', '0002_alter_producto_categoria'),
    ]

    operations = [
        migrations.CreateModel(
            name='Pedido',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('cantidad', models.IntegerField()),
                ('forma_pago', models.CharField(choices=[('credito', 'credito'), ('debito', 'debito'), ('billetera_virtual', 'billetera_virtual'), ('efectivo', 'efectivo')], default='credito', max_length=20, verbose_name='Forma de pago')),
                ('estado', models.CharField(choices=[('pendiente', 'pendiente'), ('pedido', 'pedido'), ('taller', 'taller'), ('finalizado', 'finalizado')], default='pendiente', max_length=10)),
                ('fecha_pedido', models.DateField(auto_now_add=True)),
                ('fecha_modificacion', models.DateField(auto_now=True, null=True, verbose_name='Fecha cambio de estado')),
                ('paciente', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='pacientes.paciente')),
                ('producto', models.ManyToManyField(to='ventas.Producto')),
                ('vendedor', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'pedido',
                'verbose_name_plural': 'pedidos',
            },
        ),
    ]
