# Generated by Django 3.2.5 on 2021-08-28 19:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ventas', '0004_alter_pedido_fecha_pedido'),
    ]

    operations = [
        migrations.CreateModel(
            name='LentesTipo',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(blank=True, max_length=100, null=True, verbose_name='Tipos')),
            ],
        ),
        migrations.AlterField(
            model_name='producto',
            name='categoria',
            field=models.CharField(choices=[('Lentes', 'Lentes'), ('Otros', 'Otros')], max_length=10),
        ),
        migrations.CreateModel(
            name='Lente',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('tipo', models.ManyToManyField(to='ventas.LentesTipo')),
            ],
        ),
    ]
