# Generated by Django 3.2.5 on 2021-08-28 20:07

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('ventas', '0006_auto_20210828_1622'),
    ]

    operations = [
        migrations.CreateModel(
            name='Categoria',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=100)),
            ],
        ),
        migrations.CreateModel(
            name='Subcategoria',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=100)),
            ],
        ),
        migrations.DeleteModel(
            name='LentesTipo',
        ),
        migrations.AddField(
            model_name='producto',
            name='armazon',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='producto',
            name='lente',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='producto',
            name='tipo',
            field=models.ManyToManyField(to='ventas.Subcategoria'),
        ),
        migrations.AlterField(
            model_name='producto',
            name='categoria',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='ventas.categoria'),
        ),
    ]
