# Generated by Django 3.2.5 on 2021-08-28 20:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ventas', '0007_auto_20210828_1707'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='producto',
            name='tipo',
        ),
        migrations.AddField(
            model_name='producto',
            name='distancia',
            field=models.CharField(choices=[('lejos', 'Lejos'), ('cerca', 'Cerca')], default='lejos', max_length=10, null=True),
        ),
        migrations.AddField(
            model_name='producto',
            name='lado',
            field=models.CharField(choices=[('izq', 'izq'), ('der', 'der')], default='izquierdo', max_length=10, null=True),
        ),
        migrations.DeleteModel(
            name='Subcategoria',
        ),
    ]
