# Generated by Django 3.2.5 on 2021-08-28 21:15

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('ventas', '0008_auto_20210828_1721'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='pedido',
            options={},
        ),
        migrations.RemoveField(
            model_name='pedido',
            name='cantidad',
        ),
        migrations.RemoveField(
            model_name='pedido',
            name='fecha_modificacion',
        ),
        migrations.RemoveField(
            model_name='pedido',
            name='forma_pago',
        ),
        migrations.RemoveField(
            model_name='producto',
            name='armazon',
        ),
        migrations.RemoveField(
            model_name='producto',
            name='detalles',
        ),
        migrations.RemoveField(
            model_name='producto',
            name='distancia',
        ),
        migrations.RemoveField(
            model_name='producto',
            name='imagen',
        ),
        migrations.RemoveField(
            model_name='producto',
            name='lado',
        ),
        migrations.RemoveField(
            model_name='producto',
            name='lente',
        ),
        migrations.AlterField(
            model_name='pedido',
            name='estado',
            field=models.CharField(choices=[('pendiente', 'pendiente'), ('pedido', 'pedido'), ('taller', 'taller'), ('finalizado', 'finalizado')], max_length=200, null=True),
        ),
        migrations.RemoveField(
            model_name='pedido',
            name='producto',
        ),
        migrations.AddField(
            model_name='pedido',
            name='producto',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='ventas.producto'),
        ),
        migrations.AlterField(
            model_name='producto',
            name='categoria',
            field=models.CharField(choices=[('lente', (('der', 'der'), ('izq', 'izq'), ('lejos', 'lejos'), ('cerca', 'cerca'), ('armazon', 'armazon'))), ('otra', 'otra')], max_length=10),
        ),
        migrations.DeleteModel(
            name='Categoria',
        ),
    ]
