# Generated by Django 3.2.5 on 2021-08-28 21:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ventas', '0009_auto_20210828_1815'),
    ]

    operations = [
        migrations.AlterField(
            model_name='producto',
            name='categoria',
            field=models.CharField(choices=[('lente', 'lente'), ('otra', 'otra')], max_length=10),
        ),
    ]
